### ISSUE TITLE
특정 글을 눌렀을때, "존재하지 않는 글 입니다." 라고 뜰 때가 있습니다.

### ISSUE THREAD

**Issue by samslow** [samslow/catchDeal-BE#17]
DB에서 이런 글들은 계속해서 업데이트가 되어야 할텐데 되고 있을까요 ??

**Comment by kbs4674** [comment]
처음에 글을 올렸으나, 후에 원본작성자가 삭제한 경우 그런 문제가 발생하는데 해당 상황에 대해선 아직 구현이 안되어있습니다. 다음패치 때 적용하겠습니다.

**Comment by samslow** [comment]
해결되었다면 Close 해 주세요.
다만, 현재 아직도 중복되는 글이 발견되고 있습니다. 확인하여 주세요.
product_id와 게시글 모두로 중복체크하고 계신가요 아니면 하나만 하고 계신가요 ?

**Comment by kbs4674** [comment]
현재 해당 이슈에 대해서 해결했긴 했으나, 뽐뿌 커뮤니티가 좀 불안정 합니다.
크롤러 봇이 뽐뿌에 접속할 때 종종 타임아웃과 함께 사이트 접속 자체가 안되는 문제점이 있습니다.

해당 부분은 개발을 하면서 점차 보완하겠습니다
