### ISSUE TITLE
image URL 추출 시 "https://" 문구를 꼭 붙여야 하는지 의문입니다.

### ISSUE THREAD

**Issue by kbs4674** [samslow/catchDeal-BE#20]
문제의 발단 코드 : @imageUrl 변수
```
docs = Nokogiri::HTML(open(@url))
    @time = docs.css("span.regdate").text.gsub(/\(|\)/, "").to_time - 9.hours
    @imageUrlCollect = docs.at("div.view_content").at("img").attr('src')
              
if @imageUrlCollect.include?(".jpg") || @imageUrlCollect.include?(".png") || 
    @imageUrlCollect.include?(".gif")
    @imageUrl = "http:" + "#{@imageUrlCollect}"
end
```

1. 현재 크롤링이 자료를 수집할 때, 이미지 부분은 http 혹은 https 를 생략해서 가져오는 형식입니다.
(이는 원본 자체가 http 혹은 https가 생략되어있기 때문입니다.)
예 : 
만약에 게시물 내에 `<img src="//i3.ruliweb.com/img/19/11/25/16e9fa308593a0a5e.jpg">` 로 이미지가 삽입되어 있을 경우, 크롤링은 src의 내용 부분만을 추출

2. 하지만 http 혹은 https가 빠져있더라도, `//`로서 정의하면은 전혀 이상이 없습니다.
이는 최초에 이미지파일에 접근할 때 https 가 지원이 될 경우, https로 접근하기 위해서 입니다.
    * 참고 : https://m.blog.naver.com/PostView.nhn?blogId=robinnw&logNo=220924704565&proxyReferer=https%3A%2F%2Fwww.google.com%2F

3. 강제적으로 프로토콜을 붙이는건 좋지만, 이 부분에 대해 또 하나의 문제가 발생합니다 :
게시물에 외부 URL경로를 가진 이미지를 올릴 경우, 프로토콜이 두 번 누적되어 보여지는 이슈가 있습니다.
![image](https://user-images.githubusercontent.com/19690475/69528786-4554c480-0fb2-11ea-9bca-b234a2c4f953.png)

4. 3번의 문제를 해결아기 위해 https를 강제로 붙이는 것에 대해선 생략을 했으면 좋겠습니다.

**Comment by samslow** [comment]
꼭 붙여야 합니다.
Client 에서 요청을 보낼때는 앞으로 https 로 하지 않으면 결과를 받아 올 수 없습니다.
