### ISSUE TITLE
To do List : shortDate Attribute 제거

### ISSUE THREAD

**Issue by kbs4674** [samslow/catchDeal-BE#24]
## shortDate Attribute 제거
1. 활용 목적 : -
2. 구현 계획
    * shortDate는 사실 Table Attribute가 아니다. 가상의 컬럼이라고 봐야 한다.
    * 구현방법은 간단하게도, 그냥 숨겨주면 된다.

**Comment by samslow** [comment]
이부분은 해결 된 것 같은데 자동 Close 가 안 되었네요. 제가 하겠습니다.
