### ISSUE TITLE
띄어쓰기를 고려한 검색 엔진 정확성 향상

### ISSUE THREAD

**Issue by samslow** [samslow/catchDeal-BE#32]
검색엔진이 '모던워페어' 일때는 나오지만 '모던 워 페어' 일때는 나오지 않습니다.

이런 띄어쓰기로 인한 문제를 해결 해 주세요.

**Comment by kbs4674** [comment]
확인했습니다.

**Comment by samslow** [comment]
확인하고 다음은요 ?

**Comment by kbs4674** [comment]
그간 JWT 구현, 크롤링 버그 잡느라 개발이 좀 늦어지고 있습니다..

**Comment by kbs4674** [comment]
구현 완료했습니다.
https://kbs4674.tistory.com/92
