### ISSUE TITLE
hit product 개인화 (북마크 관련)

### ISSUE THREAD

**Issue by kbs4674** [samslow/catchDeal-BE#39]
1. 현재 북마크 리스트 방식은 Book Mark 테이블에서 참조 후, 데이터를 보여주는 방식이다.
![image](https://user-images.githubusercontent.com/19690475/71540705-63d32480-2991-11ea-9c5b-a161e48e2a55.png)
![image](https://user-images.githubusercontent.com/19690475/71540709-70577d00-2991-11ea-9d73-92b83fd0c0ee.png)

2. 하지만 이러한 방식은 클라이언트 측에서 일처리를 여러번 해야하는 불편함이 존재한다.

3. 클라이언트 측의 간소화를 줄이면서도, 향후 캐치딜 메인 리스트를 열람 시(/hit-products/condition?page=1) 바로 북마크 여부를 보여줘야 하는 상황을 고려해서 북마크 시스템을 개조해야 한다.

4. 북마크 재구현 설계는 다음과 같다.
    1) 클라이언트가 `/hit-products/condition?page=1` 페이지(서버)에 접근을 시도한다.
    2) 클라이언트는 서버에 Auth JWT을 Header에 담아서 요청을 한다.
    3) 서버는 JWT 토큰에 따라 다음과 같이 구분을 한다.
        1) JWT 토큰이 있을 시 : Book Mark 테이블을 참조해서 각 Product 별로 북마크 여부를 판단하여 보여준다.
        2) JWT 토큰이 없을 시 : 북마크 여부에 대해 모두 false로 표시한다.

**Comment by samslow** [comment]
좋아요!
